PROJECT = graph_traversal_backend
PROJECT_DESCRIPTION = Graph Traversal Backend for Erlang DDD Cargo Sample
PROJECT_VERSION = 0.0.1

# Options.
CT_OPTS += -pa test -ct_hooks graph_traversal_ct_hook []

include erlang.mk
